#!/bin/sh

#
# Use these scripts to setup and develop the dotfiles in this repository.
#
# - test/00_linters: Lint the current checkout.
#
# Usage:
#   ./test/00_linters
#

# Change directory to the root of this repository.
cd "$(git rev-parse --show-toplevel)" || return

echo "=== Shellcheck ==="
_files="*/*.sh \
*/setup \
script/* \
test/*"

shellcheck -x dotfiles.sh ${_files}

echo "=== yamllint ==="
yamllint .github/workflows/*.yml
