#!/bin/sh

#
# Use these scripts to setup and develop the dotfiles in this repository.
#
# - test/00_linters: Lint the current checkout.
#
# Usage:
#   ./test/00_linters
#

# Change directory to the root of this repository.
cd "$(git rev-parse --show-toplevel)" || return

echo "=== Shellcheck ==="
_files="*/*.sh \
*/setup \
script/* \
test/*"

# shellcheck disable=SC2086
shellcheck -x dotfiles.sh ${_files}

echo "=== yamllint ==="
# TODO: Figure out how to lint YAML on GitHub-hosted runners.
#       Relevant doc: https://git.io/Jv7ZE
[ -n "$GITHUB_WORKSPACE" ] || yamllint .github/workflows/*.yml
