#!/bin/sh

#
# Use these scripts to setup and develop the dotfiles in this repository.
#
# - test/00_linters: Lint the current checkout.
#
# Usage:
#   ./test/00_linters
#

# Change directory to the root of this repository.
cd "$(git rev-parse --show-toplevel)" || exit


echo "=== Shellcheck ==="
[ -n "$(command -v shellcheck)" ] || exit
_files="*/*.sh \
*/setup \
script/* \
test/*"
# shellcheck disable=SC2086
shellcheck -x ${_files}


echo "=== yamllint ==="
[ -n "$(command -v yamllint)" ] || {
  pip3 install -U pip3 setuptools
  pip3 install yamllint
}
yamllint .github/workflows/*.yml
