#!/bin/sh

# Inspired by https://github.com/JDevlieghere/dotfiles

# Exit unless plutil and defaults are commands.
if command -v plutil >/dev/null && command -v defaults >/dev/null; then
  :
else
  exit 1
fi

# Disable smart quotes and dashes
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# Require password immediately after sleep or screen saver begins
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# Set tile and large size
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock magnification -bool true
defaults write com.apple.dock largesize -int 80
