#!/bin/sh
#
# Run `openbsd/update` to perform system and package updates and
# install new default packages.
#
# - Call openbsd/bootstrap.
# - Update the system (syspatch, fw_udpate).
# - Update packages (pkg_add -Uu).
# - Install any missing default packages.
#

DOTFILES_DEBUG=
script_name=script/update

# Initialize the warnings counter.
with_warnings=0

#
# Make sure `update` was called in a way we can get its path.
#
if [ -f "$0" ] && [ $( dirname "$0" ) ]; then
  # $0 is a file and `dirname` succeeds, so we think Yes.
  script_root="$( cd $( dirname "$0" ) && echo $PWD )"
else
  # $0 is not a file or `dirname` fails, so we think No.
  script_root=
  printf "\n[FAIL] $script_name: This script was called incorrectly. Unable to set \$script_root.\n\n"
  exit 1
fi

#
# Call dotfiles.sh to set some variables and define some functions.
#
if [ -x "$script_root/../dotfiles.sh" ]; then
  . "$script_root/../dotfiles.sh"
else
  printf "\n[FAIL] $script_name: Can't find 'dotfiles.sh'. Abort!\n\n"
  exit 1
fi

#
# Call openbsd/bootstrap
#
if [ -x "$script_root/bootstrap" ]; then
  info "$script_name: Running openbsd/bootstrap..."
  "$script_root/bootstrap"
else
  user "$script_name: Can't find openbsd/bootstrap, or it's not executable!"
  with_warnings=$(( with_warnings+1 ))
fi

#
# Update the system.
#
info "$script_name: Running \`doas syspatch\` to install system patches..."
doas syspatch

#
# Update installed packages.
#
info "$script_name: Running \`doas pkg_add -u\` to update packages..."
doas pkg_add -u

#
# Install missing default packages.
#
if [ -r "$script_root/default-packages" ]; then
  info "$script_name: Installing any missing packages from openbsd/default-packages..."
  doas pkg_add -vUl "$script_root/default-packages"
else
  user "$script_name: Can't find openbsd/default-packages, or it's not readable!"
  with_warnings=$(( with_warnings+1 ))
fi

#
# All done!
#
if [ $with_warnings -eq 0 ]; then
  success "$script_name: Finished!"
else
  success "$script_name: Finished, with $with_warnings warnings. Please resolve any '[ ?? ]' notices reported above."
fi
