#!/bin/bash
#   bootstrap - Ensure Python, pip, local install of ansible.

exit 1

echo "Verify sudo access..."
if ! sudo -v; then exit 1; fi
echo "Detect package manager..."
if grep -Eq 'Ubuntu|Debian' /etc/os-release && [ -x "$(which apt)" ]; then
  # We're running Ubuntu or Debian and `apt` is executable.
  # Make sure python3 and pip3 are available...
  echo "Detected package manager 'apt'. Ensure Python is installed..."
  sudo apt install python3 python3-pip -y
  if [ -x "$(which python3)" && -x "$(which pip3)" ]; then
    # Python and pip are available. Update tools, install Ansible...
    echo "Found Python OK. Upgrade pip, setuptools, wheel..."
    python3 -m pip install --user --upgrade pip setuptools wheel
    echo "Install and test ansible..."
    python3 -m pip install --user ansible
    source ~/.profile
    ansible -m ping localhost
  else
    # There was a problem finding or installing Python and pip.
    echo "[fail] Unable to find or install python3 and pip3."
  fi
elif grep -Eq 'CentOS' /etc/os-release && [ -x "$(which yum)" ]; then
  # We're running CentOS and yum is executable.
  # Make sure python3 and pip3 are available...
  echo "Detected package manager 'yum'. Ensure Python is installed..."
  sudo yum install -y epel-release && sudo yum check-update
  sudo yum install -y python36
  sudo ln -fs /usr/bin/python3.6 /usr/bin/python3
  python3 -m ensurepip --user --default-pip
  if [ -x "$(which python3)" ] && [ -x "$(which pip)" ]; then
    # Python and pip are available. Update tools, install Ansible...
    echo "Found Python OK. Upgrade pip, setuptools, wheel..."
    python3 -m pip install --user --upgrade pip setuptools wheel
    echo "Install and test ansible..."
    python3 -m pip install --user ansible
    ansible -m ping localhost
  else
    # There was a problem finding or installing Python and pip.
    echo "[fail] Unable to find or install python3 and pip."
  fi
else
  # Did not detect package manager.
  echo "[fail] Unable to detect package manager."
fi
