#!/bin/bash
#
# Run all dotfiles installers.

set -e

# TODO: Add debug option, like with set -x.

cd "$( dirname "$0" )/.."
dotfiles_root=$( pwd -P )
export dotfiles_root

# Run the basic installer for this OS.
my_os="$( "$dotfiles_root/bin/whichos" )"

case $my_os in
  Linux)
    if test $(which apt)
    then
      # We think we're running a Debian-based Linux, like Linux Mint.
      "$dotfiles_root/os/apt-install.sh"
    elif test $(which yum)
    then
      # We think we're running a RedHat-based Linux, like CentOS.
      "$dotfiles_root/os/yum-install.sh"
    fi
    ;;
  MacOS)
    "$dotfiles_root/os/mac-install.sh"
    ;;
  OpenBSD)
    "$dotfiles_root/os/obsd-install.sh"
    ;;
  *)
    ;;
esac

# find the installers and run them iteratively.
find . -maxdepth 2 -name 'install.sh' ! -path '*.git*' | while read installer; do "${installer}"; done
