#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run the basic installer for this OS.
sh "os/install.sh"

# find the installers and run them iteratively.
find . -maxdepth 2 -name 'install.sh' -not -path './os/*' -not -path '*.git*' | while read installer; do sh "${installer}"; done
