#!/bin/sh

#
# Use these scripts to setup and develop the dotfiles in this repository.
#
# - script/test: Test this version of these dotfiles.
#

# Change directory to the root of this repository.
cd "$(git rev-parse --show-toplevel)" || exit

# - Lint all the things.
./test/00_linters || exit
