#!/bin/sh

#
# Use these scripts to setup and develop the dotfiles in this repository.
#
# - script/update:
#
#     - Load ~/.dotfiles.conf and $DOTFILES_ROOT/dotfiles.sh.
#     - Run bootstrap and setup scripts.
#
# Usage:
#   ./script/update
#


# Load ~/.dotfiles.conf and $DOTFILES_ROOT/dotfiles.sh.
# shellcheck disable=SC1090
. ~/.dotfiles.conf || exit
"$DOTFILES_ROOT/dotfiles.sh" || exit
debug "$0: Loaded ~/.dotfiles.conf and ran $DOTFILES_ROOT/dotfiles.sh OK."


# Run bootstrap and setup scripts.

debug "$0: $DOTFILES_ROOT/script/bootstrap > /dev/null"
"$DOTFILES_ROOT/script/bootstrap" || (fail "Bootstrap failed."; exit)
debug "$0: $DOTFILES_ROOT/script/setup"
"$DOTFILES_ROOT/script/setup" || (fail "Setup failed."; exit)
