#!/bin/sh
#
# Installs the cwm(1) configuration from `$DOTFILES_ROOT/cwm`.
#
# `cwm/setup` may replace your existing `~/.xinitrc` and `~/.xsession`.
# It may also recommend changes to other configuration files.
#
# Use `$DOTFILES_ROOT/script/setup` to install `~/.cwmrc`.
#

script_name=cwm/setup

#
# Make sure `setup` was called in a way we can get its path.
#
if [ -f "$0" ] && [ $( dirname "$0" ) ]; then
  # $0 is a file and `dirname` succeeds, so we think Yes.
  script_root="$( cd $( dirname "$0" ) && echo $PWD )"
else
  # $0 is not a file or `dirname` fails, so we think No.
  script_root=
  printf "\n[FAIL] $script_name: This script was called incorrectly. Unable to set \$script_root.\n\n"
  exit 1
fi

#
# Call dotfiles.sh to set some variables and define some functions.
#
if [ -x "$script_root/../dotfiles.sh" ]; then
  . "$script_root/../dotfiles.sh"
else
  printf "\n[FAIL] $script_name: Can't find 'dotfiles.sh'. Abort!\n\n"
  exit 1
fi

# Initialize $DOTFILES_DEBUG and $with_warnings.
DOTFILES_DEBUG=
with_warnings=0

#
# Do the needful.
#

# Warn, if we're running as root.
if [ "$( id -u )" = "0" ]; then
  # We're running as root?!
  user "$script_name: This script is running as root!"
  with_warnings=$(( with_warnings+1 ))
fi

info "$script_name: Installing cwm(1) configuration files..."

# Install '.xinitrc'.
if [ -e "$HOME/.xinitrc" ]; then
  user "$script_name: '~/.xinitrc' already exists, backing it up to '~/.xinitrc.bak'..."
  with_warnings=$(( with_warnings+1 ))
  mv "$HOME/.xinitrc" "$HOME/.xinitrc.bak"
fi
if [ "$( ln -s "$DOTFILES_ROOT/cwm/.xinitrc" "$HOME/.xinitrc" 2>&1 )" = "" ]; then
  success "$script_name: Linked '~/.xinitrc' to 'cwm/.xinitrc'."
else
  fail "$script_name: Unable to link '~/.xinitrc' to 'cwm/.xinitrc'."
  with_warnings=$(( with_warnings+1 ))
fi

# Install '.xsession'.
if [ -e "$HOME/.xsession" ]; then
  user "$script_name: '~/.xsession' already exists, backing it up to '~/.xsession.bak'..."
  with_warnings=$(( with_warnings+1 ))
  mv "$HOME/.xsession" "$HOME/.xsession.bak"
fi
if [ "$( ln -s "$DOTFILES_ROOT/cwm/.xsession" "$HOME/.xsession" 2>&1 )" = "" ]; then
  success "$script_name: Linked '~/.xsession' to 'cwm/.xsession'."
else
  fail "$script_name: Unable to link '~/.xsession' to 'cwm/.xsession'."
  with_warnings=$(( with_warnings+1 ))
fi

#
# All done!
#
if [ $with_warnings -eq 0 ]; then
  success "$script_name: Finished!"
else
  success "$script_name: Finished, with $with_warnings warnings. Please resolve any '[ ?? ]' and '[FAIL]' notices reported above."
fi
